apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: frontend
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      serviceAccountName: frontend-sa
      containers:
        - name: frontend
          image: gcr.io/intern-experiment/frontend:latest
          ports:
            - containerPort: 80
          env:
            - name: PORT
              value: "80"
            - name: BACKEND_URL
              valueFrom:
                configMapKeyRef:
                  name: service-ip
                  key: backend
          resources:
            requests:
              memory: "128Mi"
              cpu: "300m"
            limits:
              memory: "256Mi"
              cpu: "750m"
