apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadgen
  namespace: frontend
  labels:
    app: loadgen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loadgen
  template:
    metadata:
      labels:
        app: loadgen
    spec:
      containers:
        - name: loadgen
          image: gcr.io/intern-experiment/loadgen
          env:
            - name: BACKEND_URL
              valueFrom:
                configMapKeyRef:
                  name: service-ip
                  key: backend
            - name: FRONTEND_ADDR
              valueFrom:
                configMapKeyRef:
                  name: service-ip
                  key: frontend
          resources:
            requests:
              memory: "128Mi"
              cpu: "300m"
            limits:
              memory: "256Mi"
              cpu: "750m"
