apiVersion: v1
kind: Service
metadata:
  name: backend-ingress
  namespace: backend
spec:
  selector:
    app: backend
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 80
  type: LoadBalancer
