# Copyright 2020 Google LLC.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# NOTE: This manifest file is made during the pre-Terraform era where all of our k8s components are created using kubectl
# It is recommended for you to manage you Kubernetes elements using Terraform instead. This manifest file may contain values specific only to our development environment, and may break as soon as you have different project names, values, etc.
# For guides on setting up your Serverless Store Kubernetes cluster, follow the main set-up guide

apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadgen
  namespace: frontend
  labels:
    app: loadgen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loadgen
  template:
    metadata:
      labels:
        app: loadgen
    spec:
      serviceAccountName: loadgen-sa
      containers:
        - name: loadgen
          image: gcr.io/intern-experiment/loadgen
          env:
            - name: BACKEND_URL
              valueFrom:
                configMapKeyRef:
                  name: service-ip
                  key: backend
            - name: FRONTEND_ADDR
              valueFrom:
                configMapKeyRef:
                  name: service-ip
                  key: frontend
          resources:
            requests:
              memory: "128Mi"
              cpu: "300m"
            limits:
              memory: "256Mi"
              cpu: "750m"
