AUTOML_MODEL_ID: ICN1320436499145031680
GCS_BUCKET: intern-project-3-storage
STRIPE_API_KEY: sk_test_51H4XF3CWiw901bJNVJkyMuJy6UFbBfkUhg9QoyaH3RRzWZWvZrmRqT5mLwPrL1FwehOjMv6jEMAZpVG2bfYIeUk600jRK5hXsA
PUBSUB_TOPIC_PAYMENT_COMPLETION: payment-completion
SENDGRID_API_KEY: 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
